### ISSUE TITLE
Order_new deprecated warning from Bravado library

### ISSUE THREAD

**Issue by kaiserex** [bybit-exchange/api-connectors#20]
When running this:
`client.Order.Order_new(side="Buy",symbol="BTCUSD",order_type="Limit",qty=1,price=8300,time_in_force="GoodTillCancel").result()`

Python shows a warning:
```
/usr/local/lib/python3.7/dist-packages/bravado/warning.py:29: Warning: [DEPRECATED] Order_new has now been deprecated. 
  warnings.warn(message, Warning)
```

What are the suggestions to resolve this?

**Comment by kaiserex** [comment]
Also:

```
/usr/local/lib/python3.7/dist-packages/bravado/warning.py:29: Warning: [DEPRECATED] Order_cancel has now been deprecated. 
    #   warnings.warn(message, Warning)
```

**Comment by sandybradley** [comment]
Same issue:

Warning: [DEPRECATED] Order_new has now been deprecated.

**Comment by sandybradley** [comment]
Solved it by using Order_newV2 instead of Order_new
i.e.
client.Order.Order_newV2(side="Buy",symbol="BTCUSD",order_type="Limit",qty=1,price=8300,time_in_force="GoodTillCancel").result()

**Comment by kaiserex** [comment]
Thanks a lot for sharing.

> Solved it by using Order_newV2 instead of Order_new
> i.e.
> client.Order.Order_newV2(side="Buy",symbol="BTCUSD",order_type="Limit",qty=1,price=8300,time_in_force="GoodTillCancel").result()
