### ISSUE TITLE
Websocket Connection

### ISSUE THREAD

**Issue by ddhb89** [bybit-exchange/api-connectors#28]
I programmed a little Python Trading Bot that works perfect on the Bybit Testnet.

But the Websocket could not connect when i switch into Live Trading
When i connect to the Live Net i get the message
Error : [Errno 101] Network is unreachable

Is there something that i did wrong?

That is the Code for the Connection with my deleted API Keys

`if doTestnet == True:
	print("Testnet Trading!")
	API_Key = "*"
	API_Secret = "*"
	wsStream = "wss://stream-testnet.bybit.com/realtime"
else:
	print("Live-Trading!")
	API_Key = "*"
	API_Secret = "*"
	wsStream = "wss://stream.bybit.com/realtime"

ws = BybitWebsocket(wsURL=wsStream, api_key=API_Key, api_secret=API_Secret)
client  = bybit.bybit(test=doTestnet, api_key=API_Key, api_secret=API_Secret)`

**Comment by ddhb89** [comment]
I solved the problem... I had to  deactivate the IPv6 support in my Router

**Comment by A-i-q-o** [comment]
Hi if anyone has similar problem you can also check this: https://github.com/bybit-exchange/api-connectors/issues/29

**Comment by botbuildtra** [comment]
This fix is not working for me

**Comment by dextertd** [comment]
Please ask me to reopen this if issue persists
