### ISSUE TITLE
"symbol is not in the range of selected"

### ISSUE THREAD

**Issue by sebastiang42** [bybit-exchange/api-connectors#31]
I've been acquainting myself with the code, and I can place orders on BTCUSD, but when I try with BTCUSDT I get the "symbol is not in the range of selected" error message. It seems that the BTCUSDT symbol has not yet been added to the python code, is this correct? Any idea when it might be added? (or if I'm making some other mistake?)

**Comment by ddhb89** [comment]
Same problem here.... every pair works except BTCUSDT

**Comment by dexter-2** [comment]
BTCUSDT will be added by the 15th.
