### ISSUE TITLE
Invalid request, please check your timestamp and recv_window param.

### ISSUE THREAD

**Issue by matteotaronna** [bybit-exchange/api-connectors#39]
help

**Comment by dexter-2** [comment]
This error occurs if your machine's clock is wrong. Try checking the time with your program just before you send the request, and then check the time sent back by the server in the response.

**Comment by matteotaronna** [comment]
thx man

**Comment by matteotaronna** [comment]
Sorry, how do I check the time sent by the server?

**Comment by dexter-2** [comment]
If possible please close your duplicate issue #41 and reopen this issue, thanks!
