### ISSUE TITLE
bind error:EOF when I called orderNewV2 in api-connector

### ISSUE THREAD

**Issue by fenny01** [bybit-exchange/api-connectors#40]
I received 'ret_msg=bind error:EOF' when I called orderNewV2

{ret_code=10001.0, ret_msg=bind error:EOF, ext_code=, ext_info=, result=null, time_now=1589719033.446360, rate_limit_status=98.0, rate_limit_reset_ms=1.589719033445E12, rate_limit=100.0}

here is my request parameter
{symbol=BTCUSD, side=Buy, time_in_force=GoodTillCancel, qty=100, order_type=Market}

Request{method=POST, url=https://api.bybit.com/v2/private/order/create?api_key=[api_key]&sign=[sign]&timestamp=1589721501986, tag=null}

**Comment by ahmad1091** [comment]
I had the same issue try to put the params in the body of the `POST` request
curl https://api.bybit.com/v2/private/order/cancel \
-H "Content-Type: application/json" \
-d '{"api_key":"{api_key}","symbol":"BTCUSD","order_id":"","timestamp":{timestamp},"sign":"{sign}"}'
