### ISSUE TITLE
How does the Set Trading-Stop function works?

### ISSUE THREAD

**Issue by matteotaronna** [bybit-exchange/api-connectors#43]
In my BybitBot, I want to put automatically the stop loss for an specific trade. I'm trying to use de client.Positions.Positions_tradingStop(), but when the trade is open it doesnt work.

Please I need some help

**Comment by dexter-2** [comment]
Are you receiving an error message?

**Comment by matteotaronna** [comment]
Nope, the function does nothing

**Comment by matteotaronna** [comment]
client.Positions.Positions_tradingStop(symbol="BTCUSD",stop_loss="8100").result()

^^ This function has to be before or after I open a buy or sell position?

**Comment by dexter-2** [comment]
After a position has been opened.

**Comment by matteotaronna** [comment]
I have it after the position, but is a Limit position. The trade has to be filled in order to the function be successful?

**Comment by dexter-2** [comment]
It's only a position once the order has been filled. Before that, it's just an order.
