### ISSUE TITLE
Cancel Conditional Trades

### ISSUE THREAD

**Issue by matteotaronna** [bybit-exchange/api-connectors#44]
Hi! How do I cancel conditional trades that has not being triggered? What function do I use?

**Comment by dexter-2** [comment]
Code:
https://github.com/bybit-exchange/api-connectors/blob/master/official-http/python/test.py#L32

Docs:
https://bybit-exchange.github.io/docs/inverse/#t-cancelcond

**Comment by matteotaronna** [comment]
bravado_core.exception.SwaggerMappingError: Conditional_cancel does not have parameter order_link_id

^^ This exception appears while using that function

**Comment by dexter-2** [comment]
Please ensure your lib is up to date. The latest version is 0.2.6.
