### ISSUE TITLE
bybit api request error occurs 10001 "invalid timestamp". help me.

### ISSUE THREAD

**Issue by KittyDragon88** [bybit-exchange/api-connectors#45]
i has created bybit api key and auto-generated javascript code by swagger operates illegal.
i according to the wallet api guide, but above error occurs.
i has created node-js server and, in it, write codes as following.

  var BybitApi = require('bybit_api');
  var defaultClient = BybitApi.ApiClient.instance;
  // Configure API key authorization: apiKey
  var apiKey = defaultClient.authentications['apiKey'];
  apiKey.apiKey = 'coxivuosidu29387249022';// example key, is valid.
  var apiSignature = defaultClient.authentications['apiSignature'];
  apiSignature.apiKey = 'coxivuosidu29387249022';// example key, is valid.
  var timestamp = defaultClient.authentications['timestamp'];
  timestamp.apiKey = 'coxivuosidu29387249022';// example key, is valid.
  var apiInstance = new BybitApi.WalletApi();
  var opts = { 
    'coin': "Coin.enum {BTC,EOS,XRP,ETH,USDT}" // String | Coin.enum {BTC,EOS,XRP,ETH,USDT}
  };
  
  apiInstance.walletGetBalance(opts, function(error, data, response) {
    if (error) {
      console.error(error);
    } else {      
      console.log('API called successfully. Returned data: ' + data);
      res.send(JSON.stringify(data));
    }
  });

**Comment by dexter-2** [comment]
Hi, this can occur if your computer's time is out of sync with the server's time. There are a number of ways to fix this, but it varies by OS.
