### ISSUE TITLE
how to get USDT balance using api-connector?

### ISSUE THREAD

**Issue by talakaz** [bybit-exchange/api-connectors#48]
There are some LinearPositions functions in test.py, but no one can fetch wallet balance, am I miss something or there is another way to do this?

**Comment by dexter-2** [comment]
print(client.Wallet.Wallet_getRecords().result())

**Comment by dexter-2** [comment]
`print(client.Wallet.Wallet_getBalance(coin="BTC").result())`

**Comment by talakaz** [comment]
> `print(client.Wallet.Wallet_getBalance(coin="BTC").result())`

It works! thanks for the reply!
