### ISSUE TITLE
bybit python lib doesn't support Order_cancelAllV2, Order_cancelAll, order_cancel_all functions

### ISSUE THREAD

**Issue by koradiyakaushal** [bybit-exchange/api-connectors#50]
AttributeError: Resource 'Order' has no operation 'cancelAll'

**Comment by dexter-2** [comment]
Please try these, they should work if you have ensured your package is using the latest version (0.2.8):

```
print(client.Order.Order_cancelV2(symbol="BTCUSD", order_id="69bd5b88-fa2e-4c33-a489-1860f595191d").result())
print(client.Order.Order_cancelAll(symbol="BTCUSD").result())
```

**Comment by koradiyakaushal** [comment]
Thanks for the help. it's working. dexter-2 where i will get all of the correct function for bybit llibrary?

**Comment by dexter-2** [comment]
https://github.com/bybit-exchange/api-connectors/blob/master/official-http/python/test.py

There are a couple mistakes in that file though, I am going to fix them next week.

**Comment by koradiyakaushal** [comment]
thanks dexyer-2 for the help. let me know once you finish the changes or let me know, from where i can refer correct methods

**Comment by dexter-2** [comment]
#54 implements a change to test.py to use the latest methods.
