### ISSUE TITLE
Please, publish your swagger object

### ISSUE THREAD

**Issue by adlai** [bybit-exchange/api-connectors#51]
Subsequent requests for improvement of the exchange's HTTP API are blocked until there is programmatic access to the source of the documentation hosted at bybit-exchange.github.io

**Comment by dexter-2** [comment]
This isn't what you're looking for?

https://github.com/bybit-exchange/api-connectors/blob/master/swagger.json

**Comment by adlai** [comment]
> This isn't what you're looking for?

Not quite!

I was looking for a parseable documentation **linked within, and hosted under, the domain of bybit.com**, and seem to have found a reasonably close approximation to my original expectations, under the /doc/swagger path. Since the link address is not contained within the link text, I'll provite it here:

https://api.bybit.com/doc/swagger/v_0_2_7.txt

However, thank you for adding the swagger.json source to this repository. That is a good step.
