### ISSUE TITLE
Please clarify documentation of the "cursor" parameter

### ISSUE THREAD

**Issue by adlai** [bybit-exchange/api-connectors#59]
In the new [/v2/private/order/list API call](https://bybit-exchange.github.io/docs/inverse/#t-getactive), the documentation for the cursor parameter is extremely unclear; simply including the cursor returned by a previous API call in the next one returns a signature validation error, regardless of whether I urlencode the cursor value.

Please clarify how to include this value, or at least show a code sample that paginates through the orders list.

**Comment by adlai** [comment]
The exact wording that needs clarification is in [lines 960](https://github.com/bybit-exchange/api-connectors/blob/master/swagger.json#L960) [and 1296](https://github.com/bybit-exchange/api-connectors/blob/master/swagger.json#L1296) of the 0.2.10 version of swagger.json:

> Use return cursor,Sign use origin data, in request please urlencode

I can understand from "Use return cursor", and from the fact that a `cursor` key is included in the object returned by this API call, that the value for this parameter, if supplied, should be the value that was returned by a previous call. I can't quite understand "Sign use origin data", nor "in request please urlencode", because there are too many different mutually exclusive interpretations of this excessively terse hint.

**Comment by pavs94** [comment]
Need an example of the same. It's ridiculous that they changed the page functionality to cursor. More ridiculous that they are changing production APIs like it's joke.

**Comment by adlai** [comment]
I managed to get the encoding step correct. The string of request parameters for signature needs to be built without the URL encoding, and the URL encoding is applied to the finished URL string including all the parameters and signatures.
