### ISSUE TITLE
order_link_id param missing from /v2/private/order swagger doc

### ISSUE THREAD

**Issue by dexter-2** [bybit-exchange/api-connectors#62]
[https://github.com/bybit-exchange/api-connectors/blob/master/swagger.json#L1119](url)

**Comment by dexter-2** [comment]
Please reopen this issue as it is on-going.

**Comment by keyganker** [comment]
Already update the swagger file.
And [the swagger file](https://api.bybit.com/doc/swagger/v_0_2_10.txt) which Python pip package use will be updated tomorrow.

**Comment by keyganker** [comment]
Done
