### ISSUE TITLE
Brand new clean install - TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by garagesteve1155** [bybit-exchange/api-connectors#68]
Here's the code giving the issue. Removed my API key and secret.

import bybit
client  = bybit.bybit(test=True, api_key="", api_secret="")

Here's the error:

Traceback (most recent call last):
  File "C:/Users/Stephen/Desktop/PowerTrader/backend/ku/bybit.py", line 2, in <module>
    import bybit
  File "C:/Users/Stephen/Desktop/PowerTrader/backend/ku\bybit.py", line 3, in <module>
    client  = bybit.bybit(test=True, api_key="", api_secret="")
TypeError: 'module' object is not callable

installed using pip, havent modified anything, so I have no clue why it wouldn't be working...

**Comment by dexter-2** [comment]
What version of `bybit` are you using? Even if it's a clean install maybe you have a `requirements.txt` which installed an old version? 

```
pip show bybit
```

0.2.10 is the latest version.

**Comment by garagesteve1155** [comment]
that's what I have. 0.2.10

**Comment by garagesteve1155** [comment]
just tried on my DO droplet as well. same error

**Comment by stevenans9859** [comment]
Same version why

**Comment by garagesteve1155** [comment]
OH MY GOD. such a dumb mistake.... I had named my script bybit.py LOLLLL
