### ISSUE TITLE
Python connector missing endpoints

### ISSUE THREAD

**Issue by dexter-2** [bybit-exchange/api-connectors#69]
```
# /v2/public/trading-records
client.Market.Market_trading_records(symbol="BTCUSD").result()
```

```
AttributeError: Resource 'Market' has no operation 'Market_trading_records'
```

In addition, the following endpoint is not swagger document and so not working with the Python connector.
```
# /v2/private/account/api-key
client.Common.Common_get().result()
```

```
AttributeError: Resource 'Common' has no operation 'Common_get'
```

Using latest version 0.2.10

**Comment by uJhin** [comment]
Method name changed:

Common_get -> Common_getTime
Market_trading_records -> Market_tradingRecords

I think it is necessary to change the API document of the old contents.
