### ISSUE TITLE
How can I get liquidated records via API which happen within 7 days?

### ISSUE THREAD

**Issue by 5QgKxT2j** [bybit-exchange/api-connectors#81]
An official API document(https://bybit-exchange.github.io/docs/inverse/?python#t-querysymbol) says "Liquidated Orders :Retrieve the liquidated orders, The query range is the last seven days of data.".
Follwoing that and specifying "from" or "start_time" parameter, it seems that latest liquidated data are always returned.
How can I get old ones?

**Comment by dextertd** [comment]
Hi, what value are you providing in your `start_time`? Please note that it should be in milliseconds, eg `1614898160961`

**Comment by adlai** [comment]
try the `/v2/public/liq-records` endpoint, and give no parameters other than the symbol; if you want fewer than the default amount of response data (five hundred trades), then you will also need to specify a sufficiently recent timestamp, because the default window is pre-computed.
