### ISSUE TITLE
Read this if your code doesn't work

### ISSUE THREAD

**Issue by oasis1234** [bybit-exchange/api-connectors#82]
Nobody is going to read this, so I won't take much effort.

Fist of all, the correct websocket URL for private subscriptions is BybitWebsocket(wsURL="wss://stream-testnet.bybit.com/realtime_private",  and not just /realtime as appears in all examples and docs. This took me one day to figure it out.

Second, the api-connectors/official-ws/python/BybitWebsocket.py needs a correction or it will give the error "expired"
  expires = str(int(round(time.time()) + 1)) + "000"    change to "0000"

What a pity a multimillion-dollar company like Bybit doesn't take the effort to fix these an another 29 issues opened since months.

**Comment by dexter-2** [comment]
Hi, this is *not* a "fix" that will make the websocket work for everyone. You are receiving this expires error because your computer's/server's time is out of sync with the bybit server time. The way to address this is at the root of the problem which is the computer's clock rather than making temporary fixes to code.

I hope this explanation makes sense, please let me know if you have any questions!

**Comment by dasAnderl** [comment]
thx to this comment only i managed to figure out why i did not receive any private msgs
url is not as stated in the documentation /realtime but as mentioned by @oasis1234 realtime_private
@dextertd please update documentation accordingly

**Comment by dextertd** [comment]
@dasAnderl It is in the documentation... https://bybit-exchange.github.io/docs/linear/#t-websocketauthentication

**Comment by dasAnderl** [comment]
true my fault in this case. i was looking/testing inverse but probably using linear pairs.
thank you for ur response. that linear and inverse have a separate apis/models does not make it easier to programm against the bybit api btw

**Comment by dextertd** [comment]
Thanks for your feedback! I completely agree, and we are working on a simplified version that will make this much easier.
