### ISSUE TITLE
Post-Only Limit order via API

### ISSUE THREAD

**Issue by JoeSham** [bybit-exchange/api-connectors#86]
Hi, when checking the API docs I cannot find anywhere how to do a Post-Only limit order (to make sure it is either a maker order or it doesn't happen otherwise). Website GUI has this feature. Is there a way to do it via API? Or will it be implemented anytime soon? Thx!

https://bybit-exchange.github.io/docs/linear/#t-placeactive

**Comment by dextertd** [comment]
https://bybit-exchange.github.io/docs/inverse_futures/#time-in-force-time_in_force

**Comment by JoeSham** [comment]
Oh, thank you!
